# Generated by Django 4.2.11 on 2024-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
            options={
                'db_table': 'books_table',
            },
        ),
    ]
